2023-01-14 17:58:30   Arguments: Namespace(aggregation='netvlad', backbone='resnet18conv4', brightness=0, cache_refresh_rate=1000, contrast=0, criterion='triplet', dataset_name='pitts30k', datasets_folder='/content', device='cuda', efficient_ram_testing=False, epochs_num=10, fc_output_dim=None, freeze_te=None, horizontal_flip=False, hue=0, infer_batch_size=16, l2='before_pool', lr=1e-05, lr_crn_layer=0.005, lr_crn_net=0.0005, majority_weight=0.01, margin=0.1, mining='partial', neg_samples_num=1000, negs_num_per_query=10, netvlad_clusters=64, num_workers=2, off_the_shelf='imagenet', optim='adam', patience=3, pca_dataset_folder=None, pca_dim=None, pretrain='imagenet', queries_per_epoch=5000, rand_perspective=0, random_resized_crop=0, random_rotation=0, recall_values=[1, 5, 10, 20], resize=[480, 640], resume='/content/drive/MyDrive/MLDL/results/synthetic_data/2023-01-14_16-01-39/last_model.pth', saturation=0, save_dir='/content/drive/MyDrive/MLDL/results/synthetic_data/2023-01-14_17-58-30', seed=0, test_method='hard_resize', train_batch_size=4, train_positives_dist_threshold=10, trunc_te=None, val_positive_dist_threshold=25)
2023-01-14 17:58:30   The outputs are being saved in /content/drive/MyDrive/MLDL/results/synthetic_data/2023-01-14_17-58-30
2023-01-14 17:58:30   Using 1 GPUs and 2 CPUs
2023-01-14 17:58:30   There are 96 queries without any positives within the training set. They won't be considered as they're useless for training.
2023-01-14 17:58:30   Train query set: < TripletsDataset, pitts30k - #database: 10000; #queries: 7320 >
2023-01-14 17:58:30   Val set: < BaseDataset, pitts30k - #database: 10000; #queries: 7608 >
2023-01-14 17:58:30   Test set: < BaseDataset, pitts30k - #database: 10000; #queries: 6816 >
2023-01-14 17:58:33   
Traceback (most recent call last):
  File "train.py", line 85, in <module>
    model, optimizer, best_r5, start_epoch_num, not_improved_num = util.resume_train(args, model, optimizer)
  File "/content/drive/MyDrive/MLDL/deep-visual-geo-localization-benchmark-main/util.py", line 59, in resume_train
    shutil.copy(args.resume.replace("last_model.pth", "best_model.pth"), args.save_dir)
  File "/usr/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/MLDL/results/synthetic_data/2023-01-14_16-01-39/best_model.pth'

